### ISSUE TITLE
A lot of 'Access Denied' errors while running

### ISSUE THREAD

**Issue by erottier** [1lann/log4shelldetect#3]
I get a lot of access denied errors on certain files on Windows (10) while running. Especially the Recycle bin and the WER files. While these are expected, it very much clutters the view.

Please filter those out and/or create a parameter to do this. (I hope it will be off and possible a parameter to turn it on)

**Comment by 1lann** [comment]
You can hide warnings by piping stderr to nul. You can do this in cmd.exe by appending ` 2>nul` and in PowerShell by appending ` 2>$nul` to your command.

For example:
```
.\log4shelldetect.exe 'C:\Program Files' 2>nul
```
(For command prompt)

Let me know if you have any other problems.
